# -*- coding: utf-8 -*-
"""ocr_llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLnkJnPJbG4qDjE_ZoKtfprnOEGkr6lX
"""

from pdf2image import convert_from_path
import pytesseract
from transformers import pipeline

pdf_file = "Bb.pdf"

pages = convert_from_path(pdf_file, dpi=300)

ocr_texts = []
for i, page in enumerate(pages):
    text = pytesseract.image_to_string(page, lang="eng")
    ocr_texts.append(text)

document_text = "\n".join(ocr_texts)

llm = pipeline("text-generation", model="tiiuae/falcon-7b-instruct", device_map="auto")

prompt = f"""
You are given OCR extracted text from the Indian Contract Act, 1872:

---
{document_text}
---

Your task:
1. Clean the OCR noise (fix spelling mistakes, remove garbage text).
2. Identify and extract important **legal terms and definitions** from the Act, such as:
   - Proposal, Acceptance, Promise, Agreement, Consideration, Contract
   - Void Contract, Voidable Contract, Illegal Agreement
   - Free Consent, Coercion, Undue Influence, Fraud, Misrepresentation, Mistake
   - Competency of Parties, Lawful Consideration, Lawful Object
   - Breach of Contract, Remedies, Damages, Quantum Meruit
   - Indemnity, Guarantee, Bailment, Pledge, Agency
3. For each term, give:
   - **Term Name**
   - **Definition (in simple language from the text)**
   - **Section Number (if available in the Act)**
4. Ignore irrelevant or noisy text.

Return the output as a structured JSON list like this:
[
  {{ "term": "Contract", "definition": "...", "section": "Section 2(h)" }},
  {{ "term": "Consideration", "definition": "...", "section": "Section 2(d)" }}
]
"""

response = llm(prompt, max_new_tokens=100, do_sample=True, temperature=0.2)
output_text = response[0]["generated_text"]

with open("filtered_output.txt", "w", encoding="utf-8") as f:
    f.write(output_text)

print("✅ Results saved in filtered_output.txt")