# -*- coding: utf-8 -*-
"""sql_query_LLM .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XL4S0h25rBO6QZzGgOcRrnET8Ga7Rzd8

#Import libraries
"""

import warnings
warnings.filterwarnings("ignore")

from sqlalchemy import create_engine, text
from langchain_community.utilities import SQLDatabase
from langchain.chains import create_sql_query_chain
from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline
import re

"""#Create the database manually"""

engine = create_engine("sqlite:///sample.db")
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS sales"))
    conn.execute(text("""
        CREATE TABLE sales (
            id INTEGER PRIMARY KEY,
            product TEXT,
            amount INTEGER
        )
    """))
    conn.execute(text("""
        INSERT INTO sales (product, amount) VALUES
        ('Laptop', 1200),
        ('Phone', 800),
        ('Tablet', 600),
        ('Phone', 900),
        ('Laptop', 1500)
    """))

"""#Import the llm model"""

db = SQLDatabase(engine)
hf_pipeline = pipeline(
    "text-generation",
    model="defog/sqlcoder-7b-2",
    device=0,
    torch_dtype="auto",
    temperature=0.0,
    max_new_tokens=100,
    do_sample=False
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

"""# Create chain"""

chain = create_sql_query_chain(llm, db)

"""#Extract the output from the chain to plain text"""

def extract_sql(text):
    # Try ```sql fenced block
    m = re.search(r"```sql(.*?)```", text, flags=re.S|re.I)
    if m:
        return m.group(1).strip()
    # Try plain SELECT ... ;
    m = re.search(r"(select .*?);", text, flags=re.S|re.I)
    if m:
        return m.group(0).strip()
    return text.strip()

"""Ask the Question to Database

"""

question = "what is the total amount?"
raw_output = chain.invoke({"question": question})

# Extract clean SQL
sql = extract_sql(raw_output)
print("🔹 Generated SQL:\n", sql)

# 6. Run SQL safely
result = db.run(sql)
print("🔹 Result:\n", result)